### ISSUE TITLE
Remove proxy items

### ISSUE THREAD

**Issue by xmha97** [Webb-L/ProxyExtensionFirefox#1]
Add a option to remove these items.
![image](https://user-images.githubusercontent.com/23485114/149405149-9f3bffb8-e74d-4304-9cb7-09a60e9fa475.png)

**Comment by Webb-L** [comment]
I'm sorry I can't listen to you on this issue. These two functions are still very useful to me.

**Comment by xmha97** [comment]
> I'm sorry I can't listen to you on this issue. These two functions are still very useful to me.

I did not say delete these items.
I say put an option that anyone can hide these items.

**Comment by Webb-L** [comment]
> > I'm sorry I can't listen to you on this issue. These two functions are still very useful to me.
> 
> I did not say delete these items. I say put an option that anyone can hide these items.

Your idea is very good. I've finished what you said.
