### ISSUE TITLE
Use Firefox default background color

### ISSUE THREAD

**Issue by xmha97** [Webb-L/ProxyExtensionFirefox#10]
Please use Firefox default background color.
![image](https://user-images.githubusercontent.com/23485114/151725061-44ea2c74-7e32-4929-a66e-8ecd10a5e8e2.png)
![image](https://user-images.githubusercontent.com/23485114/151725086-7ecbd16a-9da3-4f94-b13e-789d8f8b97fd.png)

**Comment by Webb-L** [comment]
ok

**Comment by Webb-L** [comment]
Is this ok?

![2022-02-09_20-03](https://user-images.githubusercontent.com/57182600/153197623-f8d07de3-8ef1-4eb4-8ddd-16360c197ad3.png)

**Comment by xmha97** [comment]
Yes, exactly what I want. 👌

**Comment by xmha97** [comment]
@Webb-L Please fix this color:
![image](https://user-images.githubusercontent.com/23485114/153275133-292c06a8-ad8c-4db3-91a8-5f0fd9b3175a.png)
