### ISSUE TITLE
Enable/Disable proxy with the "Manually config the proxy" switch

### ISSUE THREAD

**Issue by xmha97** [Webb-L/ProxyExtensionFirefox#12]
# 📄 Description
I have only activated the last switch.

![image](https://user-images.githubusercontent.com/23485114/153660132-70b24a66-781e-45af-a05b-2ed899ae80eb.png)

In this case, I can not disable the browser proxy.
Please add a feature to enable/disable proxy with the "Manually config the proxy" switch.

# ✔️ Expected Behavior

https://user-images.githubusercontent.com/23485114/153659261-e4dfb659-019b-45f3-bfe9-cba7078832d9.mp4

# ❌ Actual Behavior

https://user-images.githubusercontent.com/23485114/153659252-9837641e-e867-4a6a-8f10-98d2c4fd7a5a.mp4

https://user-images.githubusercontent.com/23485114/153659256-581b8a8a-84a6-4dbe-9c2b-ed8e08e9135e.mp4

**Comment by Webb-L** [comment]
If the proxy option is only manually configured. Closing the manual configuration agent cancels the configuration of the manual configuration agent.

**Comment by xmha97** [comment]
No :(

https://user-images.githubusercontent.com/23485114/153879160-e58aa400-5370-4df6-a3bc-636f5fe62616.mp4

**Comment by Webb-L** [comment]
> No :(
> 
> https://user-images.githubusercontent.com/23485114/153879160-e58aa400-5370-4df6-a3bc-636f5fe62616.mp4
> 
> 

ok

**Comment by Webb-L** [comment]
> 不 ：（
> bandicam.2022-02-14.17-36-20-122.mp4

Is that so?

https://user-images.githubusercontent.com/57182600/154075541-7cd35f32-43bb-4bd3-a5ae-be3067cd58f1.mp4

**Comment by xmha97** [comment]
Yes, but the first item should be selected when the switch is activated.

**Comment by Webb-L** [comment]
> Yes, but the first item should be selected when the switch is activated.

If the switch is on, I will set it to select the configuration option selected last time by default.

**Comment by xmha97** [comment]
Thanks, this is great.

**Comment by Webb-L** [comment]
> 谢谢，这很棒。



> Thanks, this is great.

https://user-images.githubusercontent.com/57182600/154186985-527df30f-424c-4c13-8969-2a3104ea79fc.mp4

**Comment by Webb-L** [comment]
> Thanks, this is great.

https://user-images.githubusercontent.com/57182600/154186985-527df30f-424c-4c13-8969-2a3104ea79fc.mp4

**Comment by xmha97** [comment]
> > Thanks, this is great.
> 
> 2022-02-16.10-36-01.mp4

Thanks, really great.
