### ISSUE TITLE
The language of this extension does not change

### ISSUE THREAD

**Issue by xmha97** [Webb-L/ProxyExtensionFirefox#15]
My OS (Windows) language is English.
But my Firefox language is Persian.
The language of this extension does not change to Persian :(

![image](https://user-images.githubusercontent.com/23485114/154246483-01406e68-384d-4a43-bdbf-03a4bcc1a9a7.png)

Recently I added the Persian language to this file:
https://github.com/Webb-L/ProxyExtensionFirefox/blob/master/js/language.js
I even changed the language of Firefox to Chinese, but the language of the extension is still English!

**Comment by Webb-L** [comment]
> My OS (Windows) language is English. But my Firefox language is Persian. The language of this extension does not change to Persian :(
> 
> ![image](https://user-images.githubusercontent.com/23485114/154246483-01406e68-384d-4a43-bdbf-03a4bcc1a9a7.png)
> 
> Recently I added the Persian language to this file: https://github.com/Webb-L/ProxyExtensionFirefox/blob/master/js/language.js I even changed the language of Firefox to Chinese, but the language of the extension is still English!

You can open a page randomly with your browser, press F12 and enter "navigator.language" on the console to see if it is the language of the system.


![2022-02-16_19-55](https://user-images.githubusercontent.com/57182600/154260537-c8e2a82f-594c-40c8-b0fa-c1f47b31e7a3.png)

**Comment by xmha97** [comment]
The "navigator.language" is "en-US" for me :(
![image](https://user-images.githubusercontent.com/23485114/154276645-98e38f32-baf1-4024-a68a-92c706e6e457.png)
But other extension working fine, for example:

# 1. Enhancer For YouTube
https://addons.mozilla.org/en-CA/firefox/addon/enhancer-for-youtube/
![Enhancer For YouTube](https://user-images.githubusercontent.com/23485114/154277620-7a264758-80ff-4cee-8ec7-525312432d17.png)

# 2. Dark Reader
https://addons.mozilla.org/en-CA/firefox/addon/darkreader/
![Dark Reader](https://user-images.githubusercontent.com/23485114/154278973-9d479e59-bce4-4e47-a602-b1e55fdaf09e.png)

# 3. uBlock Origin
https://addons.mozilla.org/en-CA/firefox/addon/ublock-origin/
![uBlock Origin](https://user-images.githubusercontent.com/23485114/154279177-3c7b4642-748e-4619-b10c-d583ab311313.png)

**Comment by xmha97** [comment]
Now I using ProxyExtension v1.0.9
My Firefox language is Persian but the extension language is English.
![image](https://user-images.githubusercontent.com/23485114/154934349-2c32577e-fd23-4ea6-8214-8df7b7b2f83c.png)
Please open this issue.

**Comment by Webb-L** [comment]
@xmha97 

Please input it according to the steps of my video, and then tell me the results.

`browser.i18n.getUILanguage()`

https://user-images.githubusercontent.com/57182600/154940384-413cb129-e2b3-4fac-8e2e-63c4bd0c59f2.mp4

**Comment by xmha97** [comment]
`browser.i18n.getUILanguage()` -> `fa`

![Firefox](https://user-images.githubusercontent.com/23485114/155036893-b385fbee-ca6a-4465-b9b8-082c54fe65f6.png)

**Comment by Webb-L** [comment]
@xmha97 

I updated the code of this problem, you clone it to your local, and then use `web-ext run` to see if the problem is fixed.

**web-ext:**[https://extensionworkshop.com/documentation/develop/getting-started-with-web-ext/](https://extensionworkshop.com/documentation/develop/getting-started-with-web-ext/)

**Comment by xmha97** [comment]
Thanks, now it works fine,
![image](https://user-images.githubusercontent.com/23485114/155437036-c863e55e-5091-4682-8c6f-02e62a27959b.png)

**Comment by xmha97** [comment]
I installed the latest version of this extension,
My browser language is English but the extension language is Persian.
![image](https://user-images.githubusercontent.com/23485114/157108113-2026641c-34c4-4467-981f-ce832f6e92a6.png)

**Comment by Webb-L** [comment]
> I installed the latest version of this extension, My browser language is English but the extension language is Persian. ![image](https://user-images.githubusercontent.com/23485114/157108113-2026641c-34c4-4467-981f-ce832f6e92a6.png)

The code causing this problem is at the bottom of the https://github.com/Webb-L/ProxyExtensionFirefox/blob/master/js/language.js

![image](https://user-images.githubusercontent.com/57182600/157153353-9994a1de-12a6-42f6-9d45-0a29e68dacde.png)

I store the data obtained by these three functions together, and then judge whether the language exists through the loop, and use the language if it exists.

Your problem is that the persian is at the beginning of the array.

Your problem is not a problem on my device.


https://user-images.githubusercontent.com/57182600/157152876-24993886-7dbc-47c6-a89e-a8766412cbc5.mp4
