### ISSUE TITLE
The height of the action bar is not fixed.

### ISSUE THREAD

**Issue by xmha97** [Webb-L/ProxyExtensionFirefox#17]
# 📄 Description
Hi, the height of the action bar is not fixed.

https://user-images.githubusercontent.com/23485114/154258495-8af39a39-8e65-49a5-a4ee-b90365d50c1f.mp4

Also, the settings button is not fixed.

**Comment by Webb-L** [comment]
This is a problem caused by adaptation. I don't think there is anything wrong with it. If you feel uncomfortable, I can try to modify it.

> # 📄 Description
> 
> Hi, the height of the action bar is not fixed.
> bandicam.2022-02-16.15-14-12-144.mp4
> 
> Also, the settings button is not fixed.

This is a problem caused by adaptation. I don't think there is anything wrong with it. If you feel uncomfortable, I can try to modify it.

**Comment by xmha97** [comment]
If this is not easy to fix, please close it.
