### ISSUE TITLE
Socks5 Proxy not working

### ISSUE THREAD

**Issue by xmha97** [Webb-L/ProxyExtensionFirefox#3]
You can install this addon on Android.
https://blog.mozilla.org/addons/2020/09/29/expanded-extension-support-in-firefox-for-android-nightly/

The proxy doesn't change on Android :(

![Screenshot_2022-01-16-14-41-50-922_org mozilla fenix](https://user-images.githubusercontent.com/23485114/149657566-c00b301e-42f3-40a3-8b27-770d11daf8b9.jpg)
![Screenshot_2022-01-16-14-42-01-476_org mozilla fenix](https://user-images.githubusercontent.com/23485114/149657568-d647ec6b-b892-4264-86ff-2695a0d619ee.jpg)
![Screenshot_2022-01-16-14-42-28-459_org mozilla fenix](https://user-images.githubusercontent.com/23485114/149657569-fe48bf6c-c77b-4cb5-8759-fbfeaf7aa141.jpg)

**Comment by Webb-L** [comment]
> 

Sorry, my plugin can't be used in Android.
I have just opened the about:config configuration information found in Android endfirefox, I feel that I don't support the modification of the agency settings.
I recommend you to modify the about:config configuration of Android end Firefox directly.
You can open the about:config search Proxy before the PC side, then open the Android end of the about:config reference PC side configuration.

**Comment by xmha97** [comment]
I can use the Socks5 proxy on [Telegram Desktop](https://github.com/telegramdesktop/tdesktop) and [FoxyProxy Standard](https://github.com/foxyproxy/firefox-extension) extension.

![image](https://user-images.githubusercontent.com/23485114/149683884-57d10faa-a6c3-46d9-9a80-5e106e354d45.png)

But I can't use the Socks5 proxy on your extension.

![image](https://user-images.githubusercontent.com/23485114/149684450-83e66645-caf7-4bc1-940c-add53759f6d0.png)

**Comment by Webb-L** [comment]
> I can use the Socks5 proxy on [Telegram Desktop](https://github.com/telegramdesktop/tdesktop) and [FoxyProxy Standard](https://github.com/foxyproxy/firefox-extension) extension.
> 
> ![image](https://user-images.githubusercontent.com/23485114/149683884-57d10faa-a6c3-46d9-9a80-5e106e354d45.png)
> 
> But I can't use the Socks5 proxy on your extension.
> 
> ![image](https://user-images.githubusercontent.com/23485114/149684450-83e66645-caf7-4bc1-940c-add53759f6d0.png)

Thank you for your feedback, I just tried to find your problem.
You need to remove the socks:// Firefox browser to identify your configuration.

socks://127.0.0.1:7890
to
127.0.0.1:7890

**Comment by xmha97** [comment]
OK, thanks.
