### ISSUE TITLE
Click does not work randomly

### ISSUE THREAD

**Issue by xmha97** [Webb-L/ProxyExtensionFirefox#5]
Hi @Webb-L 
Click does not work randomly!

https://user-images.githubusercontent.com/23485114/150088184-7c37f8fc-dc41-4168-a0c0-4154617a34f9.mp4

**Comment by Webb-L** [comment]
> Hi @Webb-L Click does not work randomly!
> Video.mp4

I haven't met you on my device.

https://user-images.githubusercontent.com/57182600/150093622-16667e58-4dc4-4cc6-830a-4c3db53b3632.mp4

I suggest you try using the steps I sent the video.


https://user-images.githubusercontent.com/57182600/150094358-2c57672d-9a1d-48f6-85d3-b59728f60e99.mp4

**Comment by xmha97** [comment]
I close this issue, this issue is only on my laptop!

**Comment by Webb-L** [comment]
> I close this issue, this issue is only on my laptop!



> I close this issue, this issue is only on my laptop!

Ok

**Comment by xmha97** [comment]
Which OS do you use?
I think this problem occurs in Firefox on Windows.

**Comment by Webb-L** [comment]
> Which OS do you use? I think this problem occurs in Firefox on Windows.

I use Kali Linux
I will use Windows to test later.

**Comment by xmha97** [comment]
> > Which OS do you use? I think this problem occurs in Firefox on Windows.
> 
> I use Kali Linux I will use Windows to test later.

Thanks.

**Comment by Webb-L** [comment]
> > > Which OS do you use? I think this problem occurs in Firefox on Windows.
> > 
> > 
> > I use Kali Linux I will use Windows to test later.
> 
> Thanks.

I didn't find your problem in my Windows test.
