### ISSUE TITLE
Use transparent icon for dark/light mode

### ISSUE THREAD

**Issue by xmha97** [Webb-L/ProxyExtensionFirefox#6]
Hi @Webb-L 
Please use a transparent icon for dark and light mode.
Like this extension: https://github.com/asamuzaK/sidebarTabs

Dark:
![image](https://user-images.githubusercontent.com/23485114/150568423-9dbff4b1-4b58-424f-9e69-3224902ef0e9.png)

Light:
![image](https://user-images.githubusercontent.com/23485114/150568498-c70eacad-5c03-4eb6-91fa-66ab9b04fc06.png)

manifest.json
```json
{
  "background": {
    "page": "html/background.html"
  },
  "browser_action": {
    "browser_style": true,
    "default_icon": "img/icon.svg#current",
    "default_title": "__MSG_extensionName__",
    "theme_icons": [
      {
        "dark": "img/icon.svg#dark",
        "light": "img/icon.svg#light",
        "size": 16
      },
      {
        "dark": "img/icon.svg#dark",
        "light": "img/icon.svg#light",
        "size": 32
      }
    ]
  },
```

You can use this icon for light mode: ![default-favicon](https://user-images.githubusercontent.com/23485114/150568101-8f8610be-bd19-4f75-89b0-cc4488a4179e.svg)
https://user-images.githubusercontent.com/23485114/150568101-8f8610be-bd19-4f75-89b0-cc4488a4179e.svg

**Comment by Webb-L** [comment]
I use new icons

Dark:
![image](https://user-images.githubusercontent.com/57182600/150917123-2278823e-5d0b-4c5a-9821-b8076be37522.png)

Light:
![image](https://user-images.githubusercontent.com/57182600/150917302-dfdde764-7024-40d3-a054-55178d2295d2.png)

**Comment by xmha97** [comment]
Thanks but:

Light:
![image](https://user-images.githubusercontent.com/23485114/150947169-ae7d8d6e-2859-488c-909b-0de035f0cc33.png)

Dark:
![image](https://user-images.githubusercontent.com/23485114/150947268-799e09b8-1547-4956-80a7-816ab0636d81.png)

**Comment by Webb-L** [comment]
> Thanks but:
> 
> Light: ![image](https://user-images.githubusercontent.com/23485114/150947169-ae7d8d6e-2859-488c-909b-0de035f0cc33.png)
> 
> Dark: ![image](https://user-images.githubusercontent.com/23485114/150947268-799e09b8-1547-4956-80a7-816ab0636d81.png)

The problem has been solved. Please update to the latest version

**Comment by xmha97** [comment]
Thanks.
